# Pre-define Devices
[[DeviceList]]
  Name = 'tuya-test-device'
  ProfileName = 'TestDeviceTuyaProfile'
  Description = 'tuya device is created for test purpose'
  labels = [ 'TUYA', 'test' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.tuya]
      DeviceId = "xxxxxxxxxxxx"